name: Mark Production Deployment

on:
  push:
    branches:
      - main  # Triggers whenever you push or merge to main

jobs:
  update-github-status:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: production
          initial-status: success
